### ISSUE TITLE
Package file links need URL escaping

### ISSUE THREAD

**Issue by arthurward** [nickdalt/VSHD#1]
I think the package links in the book files need URL escaping. I don't know if this is a Microsoft problem upstream or the downloader's problem, since Help Viewer can't download from the Internet due to some security policy on this machine. Help Viewer 2.3 (VS 2017) would not install anything for me, complaining that it couldn't find "V2VISUAL C#_EN-US__0.cab". I figured out that in Book-671-en-US.xml, the # sign needed URL escaping. I changed this line:
`<a class="current-link" href="Packages\V2VISUAL C#_EN-US__0.cab" />`
to this:
`<a class="current-link" href="Packages\V2VISUAL C%23_EN-US__0.cab" />`
I also did the same for the F# docs, and Help Viewer was happy.

**Comment by Ultrafeel** [comment]
I workaround it by renaming file path (but not entry name) in xml, and corresponding file name. Actually , arturward's workaround simplier.

**Comment by nickdalt** [comment]
Fixed in c3794d7d4b9f4dd75fbd4d58ba1f325b13038b5f
