### ISSUE TITLE
Package signatures are not verified

### ISSUE THREAD

**Issue by InteXX** [nickdalt/VSHD#2]
Help Content Manager indexing will fail when it can't validate a signature on a .CAB file. Therefore, the packages should be verified upon download; if a valid signature doesn't exist, the package should be downloaded again.

Here's some sample code to perform the validation:

<pre>public bool VerifySignature(string CabFileFullName)
{
  ProcessStartInfo oStartInfo = new ProcessStartInfo()
  {
    CreateNoWindow = true,
    WindowStyle = ProcessWindowStyle.Hidden,
    Arguments = $"verify /pa /q {CabFileFullName}",
    FileName = @"C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe"
  };
  Process oProcess = new Process()
  {
    StartInfo = oStartInfo
  };
  oProcess.Start();
  oProcess.WaitForExit();
  return oProcess.ExitCode == 0;
}

//=======================================================
//Service provided by Telerik (www.telerik.com)
//Conversion powered by NRefactory.
//Twitter: @telerik
//Facebook: facebook.com/telerik
//=======================================================</pre>

CLI Reference:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa387764.aspx

I'd submit a PR myself, but I'm admittedly not handy with C#.

Also: I'm not sure of the redistribution rights for SignTool, so just to be safe you may want to prompt for the file's location on the user's system.

**Comment by nickdalt** [comment]
Now checked as on 2c6de2d1ff91589d2cc2d985c0a3b282e0de2088

**Comment by InteXX** [comment]
Nice find on that `WinTrust` call...  but I'm thinking that the downloader would do better to retry a specified number of times instead of giving up after encountering the first problem. In my tests, I was able to proceed after downloading the file a second time.
