### ISSUE TITLE
Selecting VS2015 and en-US show help for VS2017

### ISSUE THREAD

**Issue by ckorn** [nickdalt/VSHD#3]
When selecting Visual Studio 2015 for en-US the list of books for Visual Studio 2017 is shown.
Other languages than en-US for VS2015 show the correct help.
![grafik](https://user-images.githubusercontent.com/1178591/27070189-30e09cec-5018-11e7-8610-0a4ebc5aa432.png)

Tested with version 1.3.1

**Comment by nickdalt** [comment]
That is what is advertised by MS as available for VS2017.
