### ISSUE TITLE
VS2013 and 2012 seems to be not working. stuck load

### ISSUE THREAD

**Issue by Ultrafeel** [nickdalt/VSHD#5]
VS2013 and 2012 seems to be not working: stuck on loading books. Workaround: download iso-s, how stated in : https://stackoverflow.com/a/13013021

**Comment by nickdalt** [comment]
I have tried with both VS2012 and VS2103 and everything downloads OK.  You will need to provide more information 

Possibly the MS servers were down

**Comment by DNS** [comment]
@nickdalt, The VS2015 & VS2017 works, but I can't download VS2012, VS2103 documentation. 
It just show _"Downloading please wait..."_. The language combo box & Load Books button are disabled (greyed) .

**Comment by Insomniator** [comment]
Same bug due new line and spaces at beginning of http://services.mtps.microsoft.com/ServiceAPI/catalogs/visualstudio11 and http://services.mtps.microsoft.com/ServiceAPI/catalogs/visualstudio12
in hex form:
0D 0A 20 20 20 20 20 20 20 20 3C3F786D6C20 <?xml....

**Comment by nickdalt** [comment]
Seems that I fixed it in 1.4.0 ([0e09c765c5fb4a299bdf745c89d3a666ee35edc5](https://github.com/nickdalt/VSHD/commit/0e09c765c5fb4a299bdf745c89d3a666ee35edc5)) but forgot to actually do a release which is why I wasn't seeing the issue.

Give the 1.4.0 release a go and see if it fixes the problem for you

**Comment by ghost199** [comment]
In the constructor of Downloader，
add this：
    `ServicePointManager.ServerCertificateValidationCallback` =
                       delegate { return true; };
    `ServicePointManager.SecurityProtocol` = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

It can solve the problem of “The underlying connection was closed: An unexpected error occurred on a send.”

**Comment by nickdalt** [comment]
The only bit that is needed is 
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

and by updating to > .NET 4.6 that issue goes away. I guess MS updated their servers to only support the newer TLS.
