### ISSUE TITLE
vs2017 lang es-ES

### ISSUE THREAD

**Issue by alex6dj** [nickdalt/VSHD#7]
When I select vs2017 and the language es-ES it only shows me help related to vs2015, I do not know if this is an error or that there is nothing else the help in English for 2017.

**Comment by nickdalt** [comment]
There are no other languages supported other than en-US at the moment. Previously the catalogs were missing so I looked at the VS2015 ones.

Fixed in 0e09c765c5fb4a299bdf745c89d3a666ee35edc5
